# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ryszard Grodzicki
title: Kotlin Developer
email: grodzicki.ryszard@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  grodzickir
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rysiek_dev
linkedin_username: rgrodzicki
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Kotlin newsletter
  icon: fas fa-newspaper
  url: https://newsletter.kotlindev.net/
# - title: another linka
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-P92HFCF"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Ryszard. I'm a Kotlin developer at Mercedes-Benz Leasing Polska. After hours I also work as a React developer at Plenti - Polish startup making a platform for lending electronic stuff.
  
  I'm a Kotlin enthusiast and I really enjoy sharing knowledge about Kotlin and promoting it among developers, especially Java developers.
  
  If you're interested in Kotlin and it's capabilities then sign up to <strong>my newsletter</strong>: https://newsletter.kotlindev.net/

  I am most skilled in: <mark>Kotlin</mark> and <mark>React</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mercedes-Benz Leasing Polska
        sub_title: Kotlin Developer
        caption: September 2018 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Plenti
        sub_title: React Developer
        caption: May 2020 - Present
        link: https://plenti.app/pl/discover
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Warsaw University of Technology 
        caption: 2013 - 2017
        sub_title: Eng. Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: In my free time
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Music (playing some guitar and piano)
      - Running
      - Video games

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
