# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ryszard Grodzicki
title: Kotlin Developer
email: grodzicki.ryszard@gmail.com
website: https://newsletter.kotlindev.net/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  grodzickir
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rysiek_dev
linkedin_username: rgrodzicki
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Kotlin newsletter
  icon: fas fa-newspaper
  url: https://newsletter.kotlindev.net/
# - title: another linka
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-P92HFCF"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Ryszard. I'm a Kotlin developer at Mercedes-Benz Leasing Polska. After hours I also work as a React developer at Plenti - Polish startup making a platform for lending electronic stuff.
  
  I'm a Kotlin enthusiast and I really enjoy sharing knowledge about Kotlin and promoting it among developers, especially Java developers.
  
  If you're interested in Kotlin and it's capabilities then sign up to <a href="https://newsletter.kotlindev.net/"><strong>my newsletter</strong></a>

  I am most skilled in: <mark>Kotlin</mark> and <mark>Spring</mark> with some <mark>React</mark> skills too

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mercedes-Benz Leasing Polska
        sub_title: Fullstack Developer (Kotlin + React)
        caption: September 2018 - Present
        description: | # this will include new lines to allow paragraphs
            Creating system for leasing or credit granting for Mercedes-Benz cars. It's stuffed with integrations and automates work for many people in the company - from the sales staff to management.
      - layout: left
        title: Plenti
        sub_title: React Developer
        caption: May 2020 - Present
        link: https://plenti.app/pl/discover
        description: |
            Helping create frontend for web app allowing to lend electronic hardware like gaming consoles, vr goggles, laptops etc. It's available throughout Poland and let's you lend the stuff for as short as few hours or as long as a year or more.
      - layout: left
        title: KartGis
        sub_title: Java/Android Developer
        caption: October 2017 - August 2018
        description: |
            Developing backend, web frontend and Android app for waterworks and sewerage companies all around Poland. All with multiple features, per-client customizations and data integrations.
      - layout: left
        title: Comarch
        sub_title: Java Developer
        caption: February 2017 - September 2017
        description: |
            Expanding and maintaining software for Polish judical system.
      - layout: left
        title: Netsprint
        sub_title: Java Developer
        caption: March 2016 - February 2017
        description: |
            Improving in-house engine for matching advertisements with users based on previously visited websites. Learned writing code with both execution speed and readability in mind.
      - layout: left
        title: Infovide-Matrix
        sub_title: Java Developer
        caption: April 2015 - March 2016
        description: |
            Firstly, as an intern 3 months were designated only for learning all of the practical development tools - version control system, build and deployment tools, project management software. Then worked on serious project in telecommunication industry.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Warsaw University of Technology 
        caption: 2013 - 2017
        sub_title: Eng. Computer Science
        quote: >
          WUT is one of the best technical universities in Poland
        description: | # this will include new lines to allow paragraphs
          I've learnt not only programming here, but also everything around it - a bit of electronics, quite a lot of math, but maybe even more important skills - teamwork and some basic project management.

  - title: In my free time
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Music (playing some guitar and piano)
      - Running
      - Video games

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
